### ISSUE TITLE
Update project files

### ISSUE THREAD

**Issue by Jonarw** [oxyplot/oxyplot-sharpdx#21]
Proposed changes:

- Update csproj files to VS2019 format
- Change target of `OxyPlot.SharpDX` to `netstandard1.1` (minimum required to use SharpDX)
- Change `OxyPlot.SharpDX.Wpf` to target both `net452` and `netcoreapp3.1`
- Change `SimpleDemo` to target `netcoreapp3.1`
- Make `CacherRenderContext` public, remove `InternalsVisibleTo.cs`. The additional encapsulation provided by this does not seem worth the effort for me, IDE support by VS2019 also seems wonky
- Update `OxyPlot.Core` reference to 2.0.0 stable

Probably this will make some changes to the CI setup necessary. Unfortunately I have next to no experience with this kind of stuff.
@objorke Do you agree with my proposed changes? If I implemented this, could you help with the CI setup?

**Comment by objorke** [comment]
This sounds very good. I can try to help with the CI part - preferably with Azure Pipelines.
